### ISSUE TITLE
Error on Manual Update (Process completed with exit code 128.)

### ISSUE THREAD

**Issue by hirotick** [kuriyan1204/atcoder-auto-clone#11]
Github初心者です。
自分のレポジトリにForkした後、Github ActionsにてManual Updateでmainブランチに対してRun workflowすると、以下のようなエラーが表示され、ACコードが取得されません。

Annonations
1error
Process completed with exit code 128.

解決策がお分かりでしたら、ご教示いただきたいです。

**Comment by kuriyan1204** [comment]
@hirotick 
GitHub Actionsのログを眺めたところ，コードの取得はできていますがリモートのレポジトリにアクセスするのに失敗しているみたいです．
![image](https://user-images.githubusercontent.com/73727292/166902183-ba17d9a1-03a8-4b21-b1ee-8b5b9e6d39c8.png)
レポジトリの名前を変更されたと思うのですが，Folk後に手動で変更されたりしましたか？
お手数お掛けしますが，今Folkされているレポジトリを削除して，もう１度Folkして試していただいても宜しいでしょうか．

**Comment by hirotick** [comment]
@kuriyan1204 
ご返答いただきありがとうございます。
再度Folkし直しましたが解決せず、こちらで再度調べたところ、workflowに対する権限が読み取り専用になっていたようです。
レポジトリの Setting→Actions→General→Workflow permissions から、読み取り・書き込みの両方を許可することで解決しました。
ありがとうございました。

**Comment by kuriyan1204** [comment]
@hirotick 
なるほど...! 権限の問題だったのですね。
自分の方では把握していなかったので、どこかに改めて書かせて頂きたいと思います！

こちらこそありがとうございました🙏
